(function() {
// 11:45 08152025 ==============================
// Step 0: Click the "Zero Cost" category first
[...document.querySelectorAll('span.category-simple-button')]
  .find(el => el.textContent.trim() === 'Zero Cost')
  ?.click();

// ==============================
// Step 1: Wait for a specific product container to appear
function waitForProductById(productId, callback, timeout = 10000) {
  const start = Date.now();
  const interval = setInterval(() => {
    const product = document.getElementById(productId);
    if (product) {
      clearInterval(interval);
      callback();
    } else if (Date.now() - start > timeout) {
      clearInterval(interval);
      console.log(`Timeout: Product with ID ${productId} not found.`);
    }
  }, 200);
}

// ==============================
// Step 2: Reusable handler for total orders and clicks
function handleProductOrders(productName, containerSelector) {
  let productLines = [...document.querySelectorAll('li.orderline')]
    .filter(li => {
      let nameEl = li.querySelector('span.product-name');
      if (!nameEl) return false;
      let nameText = nameEl.childNodes[0]?.textContent.trim();
      return nameText === productName;
    });

  if (productLines.length > 0) {
    let totalOrders = productLines.reduce((sum, li) => {
      let qtyEm = li.querySelector('ul.info-list li.info em');
      let qty = qtyEm ? parseFloat(qtyEm.textContent.trim()) : 1;
      return sum + qty;
    }, 0);

    console.log(`${productName} found with a total of ${totalOrders} order(s).`);

    let container = document.querySelector(containerSelector);
    if (container) {
      for (let i = 0; i < totalOrders; i++) {
        container.click();
      }
    } else {
      console.log(`Container for ${productName} not found.`);
    }
  } else {
    console.log(`${productName} not found.`);
  }
}

// ==============================
// Step 3: List of products to handle
const productsToHandle = [
  // Dimsum
  { name: 'DM01A FRIED FRESH PRAWN DUMPLING (3 PCS)', selector: '#article_product_5602' },
  { name: 'DM01A STEAM FRESH PRAWN DUMPLING (3 PCS)', selector: '#article_product_5602' },
  { name: 'DM01B FRIED FRESH PRAWN DUMPLING (6 PCS)', selector: '#article_product_5603' },
  { name: 'DM01B STEAM FRESH PRAWN DUMPLING (6 PCS)', selector: '#article_product_5603' },
  { name: 'DM02A FRIED POTSTICKERS (3 PCS)', selector: '#article_product_5602' },
  { name: 'DM02A STEAM POTSTICKERS (3 PCS)', selector: '#article_product_5602' },
  { name: 'DM02B FRIED POTSTICKERS (6 PCS)', selector: '#article_product_5603' },
  { name: 'DM02B STEAM POTSTICKERS (6 PCS)', selector: '#article_product_5603' },
  { name: 'DM03A FRIED WANTON 3PCS.', selector: '#article_product_5602' },
  { name: 'DM03A STEAM WANTON 3PCS.', selector: '#article_product_5602' },
  { name: 'DM03B FRIED WANTON 6PCS.', selector: '#article_product_5603' },
  { name: 'DM03B STEAM WANTON 6PCS.', selector: '#article_product_5603' },
  { name: 'DM04 SHANGHAI ROLLS 5', selector: '#article_product_5603' },
  { name: 'DM05A PINSEC FRITO 4', selector: '#article_product_5603' },
  { name: 'DM05B PINSEC FRITO 8', selector: '#article_product_5603' },
  { name: 'DM05C PINSEC FRITO 24', selector: '#article_product_5607' },
  { name: 'DM09 TOFU IN BBQ SAUCE', selector: '#article_product_5603' },
  { name: 'DM10 CHICKEN FEET', selector: '#article_product_5602' },
  { name: 'DM11 C.EGG & J.FISH SALAD', selector: '#article_product_5603' },
  { name: 'DM12 FRIED SAVORY TAHO SQ', selector: '#article_product_5602' },
  { name: 'DM13 FRIED SHARKSFIN SIOMAI 4', selector: '#article_product_5602' },
  { name: 'DM13 STEAM SHARKSFIN SIOMAI 4', selector: '#article_product_5602' },
  { name: 'DM15A SIOMAI (4 PCS)', selector: '#article_product_5602' },
  { name: 'DM15B SIOMAI (12 PCS)', selector: '#article_product_5606' },
  { name: 'DM16A KIKIAM (1 PC)', selector: '#article_product_5603' },
  { name: 'DM16B KIKIAM (2 PCS)', selector: '#article_product_5603' },
  // Hongkong Noodles
  { name: 'NS01L NANKING BEEF LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS01R NANKING BEEF RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS02L BEEF TENDON LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS02R BEEF TENDON RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS03L PRAWN DUMPLING LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS03R PRAWN DUMPLING RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS04L WANTON LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS04R WANTON RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS05L 3KINDS MUSHROOM LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS05R 3KINDS MUSHROOM RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS06L DOUBLE PORK RIB LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS06R DOUBLE PORK RIB RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS07L NANKING BF/WANTON LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS07R NANKING BF/WANTON RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS08L BEEF TNDON/WANTON LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS08R BEEF TNDON/WANTON RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS09L PRWN DM/NNKING BF LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS09R PRWN DM/NNKING BF RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS10L PRWN DM/MUSHROOM LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS10R PRWN DM/MUSHROOM RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS11L PRWN DM/BF TNDON LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS11R PRWN DM/BF TNDON RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS12L WANTON/MUSHROOM LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS12R WANTON/MUSHROOM RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS13L NANKING BF/TNDON LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS13R NANKING BF/TNDON RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS14L PORK RIB/PRWN DM LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS14R PORK RIB/PRWN DM RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS15L PORK RIB/WANTON LP HONGKONG NOODLES', selector: '#article_product_5604' },
  { name: 'NS15R PORK RIB/WANTON RG HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS88 ULTIMATE NOODLES HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS90 WHITE CHICKEN HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS91 SOY CHICKEN HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'NS92 PLAIN HONGKONG NOODLES', selector: '#article_product_8969' },
  // HONGKONG INSERT BOWL
  { name: 'NS01L NANKING BEEF LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS01R NANKING BEEF RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS02L BEEF TENDON LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS02R BEEF TENDON RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS03L PRAWN DUMPLING LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS03R PRAWN DUMPLING RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS04L WANTON LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS04R WANTON RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS05L 3KINDS MUSHROOM LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS05R 3KINDS MUSHROOM RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS06L DOUBLE PORK RIB LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS06R DOUBLE PORK RIB RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS07L NANKING BF/WANTON LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS07R NANKING BF/WANTON RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS08L BEEF TNDON/WANTON LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS08R BEEF TNDON/WANTON RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS09L PRWN DM/NNKING BF LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS09R PRWN DM/NNKING BF RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS10L PRWN DM/MUSHROOM LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS10R PRWN DM/MUSHROOM RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS11L PRWN DM/BF TNDON LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS11R PRWN DM/BF TNDON RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS12L WANTON/MUSHROOM LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS12R WANTON/MUSHROOM RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS13L NANKING BF/TNDON LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS13R NANKING BF/TNDON RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS14L PORK RIB/PRWN DM LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS14R PORK RIB/PRWN DM RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS15L PORK RIB/WANTON LP HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS15R PORK RIB/WANTON RG HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS88 ULTIMATE NOODLES HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS90 WHITE CHICKEN HONGKONG NOODLES', selector: '#article_product_8969' },
  { name: 'NS91 SOY CHICKEN HONGKONG NOODLES', selector: '#article_product_8969' },
  // HONGKONG CHOPSTICK
  { name: 'NS01L NANKING BEEF LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS01R NANKING BEEF RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS02L BEEF TENDON LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS02R BEEF TENDON RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS03L PRAWN DUMPLING LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS03R PRAWN DUMPLING RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS04L WANTON LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS04R WANTON RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS05L 3KINDS MUSHROOM LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS05R 3KINDS MUSHROOM RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS06L DOUBLE PORK RIB LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS06R DOUBLE PORK RIB RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS07L NANKING BF/WANTON LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS07R NANKING BF/WANTON RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS08L BEEF TNDON/WANTON LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS08R BEEF TNDON/WANTON RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS09L PRWN DM/NNKING BF LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS09R PRWN DM/NNKING BF RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS10L PRWN DM/MUSHROOM LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS10R PRWN DM/MUSHROOM RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS11L PRWN DM/BF TNDON LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS11R PRWN DM/BF TNDON RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS12L WANTON/MUSHROOM LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS12R WANTON/MUSHROOM RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS13L NANKING BF/TNDON LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS13R NANKING BF/TNDON RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS14L PORK RIB/PRWN DM LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS14R PORK RIB/PRWN DM RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS15L PORK RIB/WANTON LP HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS15R PORK RIB/WANTON RG HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS88 ULTIMATE NOODLES HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS90 WHITE CHICKEN HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS91 SOY CHICKEN HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'NS92 PLAIN HONGKONG NOODLES', selector: '#article_product_13937' },
  // Canton Noodles 
  { name: 'NS01L NANKING BEEF LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS01R NANKING BEEF RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS02L BEEF TENDON LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS02R BEEF TENDON RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS03L PRAWN DUMPLING LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS03R PRAWN DUMPLING RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS04L WANTON LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS04R WANTON RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS05L 3KINDS MUSHROOM LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS05R 3KINDS MUSHROOM RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS06L DOUBLE PORK RIB LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS06R DOUBLE PORK RIB RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS07L NANKING BF/WANTON LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS07R NANKING BF/WANTON RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS08L BEEF TNDON/WANTON LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS08R BEEF TNDON/WANTON RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS09L PRWN DM/NNKING BF LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS09R PRWN DM/NNKING BF RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS10L PRWN DM/MUSHROOM LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS10R PRWN DM/MUSHROOM RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS11L PRWN DM/BF TNDON LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS11R PRWN DM/BF TNDON RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS12L WANTON/MUSHROOM LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS12R WANTON/MUSHROOM RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS13L NANKING BF/TNDON LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS13R NANKING BF/TNDON RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS14L PORK RIB/PRWN DM LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS14R PORK RIB/PRWN DM RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS15L PORK RIB/WANTON LP CANTON NOODLES', selector: '#article_product_5604' },
  { name: 'NS15R PORK RIB/WANTON RG CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS88 ULTIMATE NOODLES CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS90 WHITE CHICKEN CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS91 SOY CHICKEN CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'NS92 PLAIN CANTON NOODLES', selector: '#article_product_8969' } ,
  // Canton Insert Bowl 
  { name: 'NS01L NANKING BEEF LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS01R NANKING BEEF RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS02L BEEF TENDON LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS02R BEEF TENDON RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS03L PRAWN DUMPLING LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS03R PRAWN DUMPLING RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS04L WANTON LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS04R WANTON RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS05L 3KINDS MUSHROOM LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS05R 3KINDS MUSHROOM RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS06L DOUBLE PORK RIB LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS06R DOUBLE PORK RIB RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS07L NANKING BF/WANTON LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS07R NANKING BF/WANTON RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS08L BEEF TNDON/WANTON LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS08R BEEF TNDON/WANTON RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS09L PRWN DM/NNKING BF LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS09R PRWN DM/NNKING BF RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS10L PRWN DM/MUSHROOM LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS10R PRWN DM/MUSHROOM RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS11L PRWN DM/BF TNDON LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS11R PRWN DM/BF TNDON RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS12L WANTON/MUSHROOM LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS12R WANTON/MUSHROOM RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS13L NANKING BF/TNDON LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS13R NANKING BF/TNDON RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS14L PORK RIB/PRWN DM LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS14R PORK RIB/PRWN DM RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS15L PORK RIB/WANTON LP CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS15R PORK RIB/WANTON RG CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS88 ULTIMATE NOODLES CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS90 WHITE CHICKEN CANTON NOODLES', selector: '#article_product_8969' },
  { name: 'NS91 SOY CHICKEN CANTON NOODLES', selector: '#article_product_8969' },
  // Canton CHOPSTICK
  { name: 'NS01L NANKING BEEF LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS01R NANKING BEEF RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS02L BEEF TENDON LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS02R BEEF TENDON RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS03L PRAWN DUMPLING LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS03R PRAWN DUMPLING RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS04L WANTON LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS04R WANTON RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS05L 3KINDS MUSHROOM LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS05R 3KINDS MUSHROOM RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS06L DOUBLE PORK RIB LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS06R DOUBLE PORK RIB RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS07L NANKING BF/WANTON LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS07R NANKING BF/WANTON RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS08L BEEF TNDON/WANTON LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS08R BEEF TNDON/WANTON RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS09L PRWN DM/NNKING BF LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS09R PRWN DM/NNKING BF RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS10L PRWN DM/MUSHROOM LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS10R PRWN DM/MUSHROOM RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS11L PRWN DM/BF TNDON LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS11R PRWN DM/BF TNDON RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS12L WANTON/MUSHROOM LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS12R WANTON/MUSHROOM RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS13L NANKING BF/TNDON LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS13R NANKING BF/TNDON RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS14L PORK RIB/PRWN DM LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS14R PORK RIB/PRWN DM RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS15L PORK RIB/WANTON LP CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS15R PORK RIB/WANTON RG CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS88 ULTIMATE NOODLES CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS90 WHITE CHICKEN CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS91 SOY CHICKEN CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'NS92 PLAIN CANTON NOODLES', selector: '#article_product_13937' } ,
  // Flat Shanghai Noodles
  { name: 'NS01L NANKING BEEF LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS01R NANKING BEEF RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS02L BEEF TENDON LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS02R BEEF TENDON RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS03L PRAWN DUMPLING LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS03R PRAWN DUMPLING RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS04L WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS04R WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS05L 3KINDS MUSHROOM LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS05R 3KINDS MUSHROOM RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS06L DOUBLE PORK RIB LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS06R DOUBLE PORK RIB RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS07L NANKING BF/WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS07R NANKING BF/WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS08L BEEF TNDON/WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS08R BEEF TNDON/WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS09L PRWN DM/NNKING BF LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS09R PRWN DM/NNKING BF RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS10L PRWN DM/MUSHROOM LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS10R PRWN DM/MUSHROOM RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS11L PRWN DM/BF TNDON LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS11R PRWN DM/BF TNDON RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS12L WANTON/MUSHROOM LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS12R WANTON/MUSHROOM RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS13L NANKING BF/TNDON LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS13R NANKING BF/TNDON RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS14L PORK RIB/PRWN DM LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS14R PORK RIB/PRWN DM RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS15L PORK RIB/WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_5604' },
  { name: 'NS15R PORK RIB/WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS88 ULTIMATE NOODLES FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS90 WHITE CHICKEN FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS91 SOY CHICKEN FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'NS92 PLAIN FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  // Flat Shanghai Noodles Insert Bowl
  { name: 'NS01L NANKING BEEF LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS01R NANKING BEEF RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS02L BEEF TENDON LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS02R BEEF TENDON RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS03L PRAWN DUMPLING LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS03R PRAWN DUMPLING RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS04L WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS04R WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS05L 3KINDS MUSHROOM LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS05R 3KINDS MUSHROOM RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS06L DOUBLE PORK RIB LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS06R DOUBLE PORK RIB RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS07L NANKING BF/WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS07R NANKING BF/WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS08L BEEF TNDON/WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS08R BEEF TNDON/WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS09L PRWN DM/NNKING BF LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS09R PRWN DM/NNKING BF RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS10L PRWN DM/MUSHROOM LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS10R PRWN DM/MUSHROOM RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS11L PRWN DM/BF TNDON LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS11R PRWN DM/BF TNDON RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS12L WANTON/MUSHROOM LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS12R WANTON/MUSHROOM RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS13L NANKING BF/TNDON LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS13R NANKING BF/TNDON RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS14L PORK RIB/PRWN DM LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS14R PORK RIB/PRWN DM RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS15L PORK RIB/WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS15R PORK RIB/WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS88 ULTIMATE NOODLES FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS90 WHITE CHICKEN FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  { name: 'NS91 SOY CHICKEN FLAT SHANGHAI NOODLES', selector: '#article_product_8969' },
  // Flat Shanghai Noodles CHOPSTICK
  { name: 'NS01L NANKING BEEF LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS01R NANKING BEEF RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS02L BEEF TENDON LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS02R BEEF TENDON RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS03L PRAWN DUMPLING LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS03R PRAWN DUMPLING RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS04L WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS04R WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS05L 3KINDS MUSHROOM LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS05R 3KINDS MUSHROOM RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS06L DOUBLE PORK RIB LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS06R DOUBLE PORK RIB RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS07L NANKING BF/WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS07R NANKING BF/WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS08L BEEF TNDON/WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS08R BEEF TNDON/WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS09L PRWN DM/NNKING BF LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS09R PRWN DM/NNKING BF RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS10L PRWN DM/MUSHROOM LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS10R PRWN DM/MUSHROOM RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS11L PRWN DM/BF TNDON LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS11R PRWN DM/BF TNDON RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS12L WANTON/MUSHROOM LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS12R WANTON/MUSHROOM RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS13L NANKING BF/TNDON LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS13R NANKING BF/TNDON RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS14L PORK RIB/PRWN DM LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS14R PORK RIB/PRWN DM RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS15L PORK RIB/WANTON LP FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS15R PORK RIB/WANTON RG FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS88 ULTIMATE NOODLES FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS90 WHITE CHICKEN FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS91 SOY CHICKEN FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'NS92 PLAIN FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  // Herb Noodles
  { name: 'NS01L NANKING BEEF LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS01R NANKING BEEF RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS02L BEEF TENDON LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS02R BEEF TENDON RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS03L PRAWN DUMPLING LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS03R PRAWN DUMPLING RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS04L WANTON LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS04R WANTON RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS05L 3KINDS MUSHROOM LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS05R 3KINDS MUSHROOM RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS06L DOUBLE PORK RIB LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS06R DOUBLE PORK RIB RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS07L NANKING BF/WANTON LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS07R NANKING BF/WANTON RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS08L BEEF TNDON/WANTON LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS08R BEEF TNDON/WANTON RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS09L PRWN DM/NNKING BF LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS09R PRWN DM/NNKING BF RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS10L PRWN DM/MUSHROOM LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS10R PRWN DM/MUSHROOM RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS11L PRWN DM/BF TNDON LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS11R PRWN DM/BF TNDON RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS12L WANTON/MUSHROOM LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS12R WANTON/MUSHROOM RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS13L NANKING BF/TNDON LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS13R NANKING BF/TNDON RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS14L PORK RIB/PRWN DM LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS14R PORK RIB/PRWN DM RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS15L PORK RIB/WANTON LP HERB NOODLES', selector: '#article_product_5604' },
  { name: 'NS15R PORK RIB/WANTON RG HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS88 ULTIMATE NOODLES HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS90 WHITE CHICKEN HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS91 SOY CHICKEN HERB NOODLES', selector: '#article_product_5605' },
  { name: 'NS92 PLAIN HERB NOODLES', selector: '#article_product_8969' },
  // Herb Noodles Insert Bowl
  { name: 'NS01L NANKING BEEF LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS01R NANKING BEEF RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS02L BEEF TENDON LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS02R BEEF TENDON RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS03L PRAWN DUMPLING LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS03R PRAWN DUMPLING RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS04L WANTON LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS04R WANTON RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS05L 3KINDS MUSHROOM LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS05R 3KINDS MUSHROOM RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS06L DOUBLE PORK RIB LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS06R DOUBLE PORK RIB RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS07L NANKING BF/WANTON LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS07R NANKING BF/WANTON RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS08L BEEF TNDON/WANTON LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS08R BEEF TNDON/WANTON RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS09L PRWN DM/NNKING BF LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS09R PRWN DM/NNKING BF RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS10L PRWN DM/MUSHROOM LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS10R PRWN DM/MUSHROOM RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS11L PRWN DM/BF TNDON LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS11R PRWN DM/BF TNDON RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS12L WANTON/MUSHROOM LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS12R WANTON/MUSHROOM RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS13L NANKING BF/TNDON LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS13R NANKING BF/TNDON RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS14L PORK RIB/PRWN DM LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS14R PORK RIB/PRWN DM RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS15L PORK RIB/WANTON LP HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS15R PORK RIB/WANTON RG HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS88 ULTIMATE NOODLES HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS90 WHITE CHICKEN HERB NOODLES', selector: '#article_product_8969' },
  { name: 'NS91 SOY CHICKEN HERB NOODLES', selector: '#article_product_8969' },
  // Herb Noodles CHOPSTICK
  { name: 'NS01L NANKING BEEF LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS01R NANKING BEEF RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS02L BEEF TENDON LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS02R BEEF TENDON RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS03L PRAWN DUMPLING LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS03R PRAWN DUMPLING RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS04L WANTON LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS04R WANTON RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS05L 3KINDS MUSHROOM LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS05R 3KINDS MUSHROOM RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS06L DOUBLE PORK RIB LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS06R DOUBLE PORK RIB RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS07L NANKING BF/WANTON LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS07R NANKING BF/WANTON RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS08L BEEF TNDON/WANTON LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS08R BEEF TNDON/WANTON RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS09L PRWN DM/NNKING BF LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS09R PRWN DM/NNKING BF RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS10L PRWN DM/MUSHROOM LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS10R PRWN DM/MUSHROOM RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS11L PRWN DM/BF TNDON LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS11R PRWN DM/BF TNDON RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS12L WANTON/MUSHROOM LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS12R WANTON/MUSHROOM RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS13L NANKING BF/TNDON LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS13R NANKING BF/TNDON RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS14L PORK RIB/PRWN DM LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS14R PORK RIB/PRWN DM RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS15L PORK RIB/WANTON LP HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS15R PORK RIB/WANTON RG HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS88 ULTIMATE NOODLES HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS90 WHITE CHICKEN HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS91 SOY CHICKEN HERB NOODLES', selector: '#article_product_13937' },
  { name: 'NS92 PLAIN HERB NOODLES', selector: '#article_product_13937' },
  // Empress Noodles
  { name: 'NS01L NANKING BEEF LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS01R NANKING BEEF RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS02L BEEF TENDON LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS02R BEEF TENDON RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS03L PRAWN DUMPLING LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS03R PRAWN DUMPLING RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS04L WANTON LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS04R WANTON RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS05L 3KINDS MUSHROOM LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS05R 3KINDS MUSHROOM RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS06L DOUBLE PORK RIB LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS06R DOUBLE PORK RIB RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS07L NANKING BF/WANTON LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS07R NANKING BF/WANTON RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS08L BEEF TNDON/WANTON LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS08R BEEF TNDON/WANTON RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS09L PRWN DM/NNKING BF LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS09R PRWN DM/NNKING BF RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS10L PRWN DM/MUSHROOM LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS10R PRWN DM/MUSHROOM RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS11L PRWN DM/BF TNDON LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS11R PRWN DM/BF TNDON RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS12L WANTON/MUSHROOM LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS12R WANTON/MUSHROOM RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS13L NANKING BF/TNDON LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS13R NANKING BF/TNDON RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS14L PORK RIB/PRWN DM LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS14R PORK RIB/PRWN DM RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS15L PORK RIB/WANTON LP EMPRESS NOODLES', selector: '#article_product_5604' },
  { name: 'NS15R PORK RIB/WANTON RG EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS88 ULTIMATE NOODLES EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS90 WHITE CHICKEN EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS91 SOY CHICKEN EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'NS92 PLAIN EMPRESS NOODLES', selector: '#article_product_8969' },  
  // Empress Noodles Insert Bowl
  { name: 'NS01L NANKING BEEF LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS01R NANKING BEEF RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS02L BEEF TENDON LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS02R BEEF TENDON RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS03L PRAWN DUMPLING LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS03R PRAWN DUMPLING RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS04L WANTON LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS04R WANTON RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS05L 3KINDS MUSHROOM LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS05R 3KINDS MUSHROOM RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS06L DOUBLE PORK RIB LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS06R DOUBLE PORK RIB RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS07L NANKING BF/WANTON LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS07R NANKING BF/WANTON RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS08L BEEF TNDON/WANTON LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS08R BEEF TNDON/WANTON RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS09L PRWN DM/NNKING BF LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS09R PRWN DM/NNKING BF RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS10L PRWN DM/MUSHROOM LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS10R PRWN DM/MUSHROOM RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS11L PRWN DM/BF TNDON LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS11R PRWN DM/BF TNDON RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS12L WANTON/MUSHROOM LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS12R WANTON/MUSHROOM RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS13L NANKING BF/TNDON LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS13R NANKING BF/TNDON RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS14L PORK RIB/PRWN DM LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS14R PORK RIB/PRWN DM RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS15L PORK RIB/WANTON LP EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS15R PORK RIB/WANTON RG EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS88 ULTIMATE NOODLES EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS90 WHITE CHICKEN EMPRESS NOODLES', selector: '#article_product_8969' },
  { name: 'NS91 SOY CHICKEN EMPRESS NOODLES', selector: '#article_product_8969' },
  // Empress Noodles CHOPSTICK
  { name: 'NS01L NANKING BEEF LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS01R NANKING BEEF RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS02L BEEF TENDON LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS02R BEEF TENDON RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS03L PRAWN DUMPLING LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS03R PRAWN DUMPLING RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS04L WANTON LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS04R WANTON RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS05L 3KINDS MUSHROOM LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS05R 3KINDS MUSHROOM RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS06L DOUBLE PORK RIB LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS06R DOUBLE PORK RIB RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS07L NANKING BF/WANTON LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS07R NANKING BF/WANTON RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS08L BEEF TNDON/WANTON LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS08R BEEF TNDON/WANTON RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS09L PRWN DM/NNKING BF LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS09R PRWN DM/NNKING BF RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS10L PRWN DM/MUSHROOM LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS10R PRWN DM/MUSHROOM RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS11L PRWN DM/BF TNDON LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS11R PRWN DM/BF TNDON RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS12L WANTON/MUSHROOM LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS12R WANTON/MUSHROOM RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS13L NANKING BF/TNDON LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS13R NANKING BF/TNDON RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS14L PORK RIB/PRWN DM LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS14R PORK RIB/PRWN DM RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS15L PORK RIB/WANTON LP EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS15R PORK RIB/WANTON RG EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS88 ULTIMATE NOODLES EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS90 WHITE CHICKEN EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS91 SOY CHICKEN EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'NS92 PLAIN EMPRESS NOODLES', selector: '#article_product_13937' },  
  // Whole wheat Noodles
  { name: 'NS01L NANKING BEEF LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS01R NANKING BEEF RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS02L BEEF TENDON LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS02R BEEF TENDON RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS03L PRAWN DUMPLING LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS03R PRAWN DUMPLING RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS04L WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS04R WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS05L 3KINDS MUSHROOM LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS05R 3KINDS MUSHROOM RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS06L DOUBLE PORK RIB LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS06R DOUBLE PORK RIB RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS07L NANKING BF/WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS07R NANKING BF/WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS08L BEEF TNDON/WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS08R BEEF TNDON/WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS09L PRWN DM/NNKING BF LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS09R PRWN DM/NNKING BF RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS10L PRWN DM/MUSHROOM LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS10R PRWN DM/MUSHROOM RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS11L PRWN DM/BF TNDON LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS11R PRWN DM/BF TNDON RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS12L WANTON/MUSHROOM LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS12R WANTON/MUSHROOM RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS13L NANKING BF/TNDON LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS13R NANKING BF/TNDON RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS14L PORK RIB/PRWN DM LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS14R PORK RIB/PRWN DM RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS15L PORK RIB/WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_5604' },
  { name: 'NS15R PORK RIB/WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS88 ULTIMATE NOODLES WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS90 WHITE CHICKEN WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS91 SOY CHICKEN WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'NS92 PLAIN WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  // Whole wheat Noodles Insert Bowl
  { name: 'NS01L NANKING BEEF LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS01R NANKING BEEF RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS02L BEEF TENDON LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS02R BEEF TENDON RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS03L PRAWN DUMPLING LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS03R PRAWN DUMPLING RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS04L WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS04R WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS05L 3KINDS MUSHROOM LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS05R 3KINDS MUSHROOM RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS06L DOUBLE PORK RIB LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS06R DOUBLE PORK RIB RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS07L NANKING BF/WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS07R NANKING BF/WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS08L BEEF TNDON/WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS08R BEEF TNDON/WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS09L PRWN DM/NNKING BF LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS09R PRWN DM/NNKING BF RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS10L PRWN DM/MUSHROOM LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS10R PRWN DM/MUSHROOM RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS11L PRWN DM/BF TNDON LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS11R PRWN DM/BF TNDON RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS12L WANTON/MUSHROOM LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS12R WANTON/MUSHROOM RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS13L NANKING BF/TNDON LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS13R NANKING BF/TNDON RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS14L PORK RIB/PRWN DM LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS14R PORK RIB/PRWN DM RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS15L PORK RIB/WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS15R PORK RIB/WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS88 ULTIMATE NOODLES WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS90 WHITE CHICKEN WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  { name: 'NS91 SOY CHICKEN WHOLE WHEAT NOODLES', selector: '#article_product_8969' },
  // Whole wheat Noodles CHOPSTICK
  { name: 'NS01L NANKING BEEF LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS01R NANKING BEEF RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS02L BEEF TENDON LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS02R BEEF TENDON RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS03L PRAWN DUMPLING LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS03R PRAWN DUMPLING RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS04L WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS04R WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS05L 3KINDS MUSHROOM LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS05R 3KINDS MUSHROOM RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS06L DOUBLE PORK RIB LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS06R DOUBLE PORK RIB RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS07L NANKING BF/WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS07R NANKING BF/WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS08L BEEF TNDON/WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS08R BEEF TNDON/WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS09L PRWN DM/NNKING BF LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS09R PRWN DM/NNKING BF RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS10L PRWN DM/MUSHROOM LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS10R PRWN DM/MUSHROOM RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS11L PRWN DM/BF TNDON LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS11R PRWN DM/BF TNDON RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS12L WANTON/MUSHROOM LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS12R WANTON/MUSHROOM RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS13L NANKING BF/TNDON LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS13R NANKING BF/TNDON RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS14L PORK RIB/PRWN DM LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS14R PORK RIB/PRWN DM RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS15L PORK RIB/WANTON LP WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS15R PORK RIB/WANTON RG WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS16 SZCHUAN TAN TAN MIEN WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS88 ULTIMATE NOODLES WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS90 WHITE CHICKEN WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS91 SOY CHICKEN WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'NS92 PLAIN WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  // Hongkong BN
  { name: 'BN17 NANKING BEEF HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'BN18 ANISEED BEEF TENDON HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'BN19 WANTON HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'BN20 FRESH PRAWN DUMPLING HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'BN21 3KINDS MUSHROOM HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'BN22 DOUBLE PORK RIB HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'BN23 SZE TANTAN MIEN HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'BN90 BN MIX HONGKONG NOODLES', selector: '#article_product_5605' },
  { name: 'BN92 PLAIN CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'BN92 PLAIN HONGKONG NOODLES', selector: '#article_product_5605' },
  // Hongkong BN SOUP
  { name: 'BN17 NANKING BEEF HONGKONG NOODLES', selector: '#article_product_5602' },
  { name: 'BN18 ANISEED BEEF TENDON HONGKONG NOODLES', selector: '#article_product_5602' },
  { name: 'BN19 WANTON HONGKONG NOODLES', selector: '#article_product_5602' },
  { name: 'BN20 FRESH PRAWN DUMPLING HONGKONG NOODLES', selector: '#article_product_5602' },
  { name: 'BN21 3KINDS MUSHROOM HONGKONG NOODLES', selector: '#article_product_5602' },
  { name: 'BN22 DOUBLE PORK RIB HONGKONG NOODLES', selector: '#article_product_5602' },
  { name: 'BN23 SZE TANTAN MIEN HONGKONG NOODLES', selector: '#article_product_5602' },
  { name: 'BN90 BN MIX HONGKONG NOODLES', selector: '#article_product_5602' },
  { name: 'BN92 PLAIN CANTON NOODLES', selector: '#article_product_5602' },
  { name: 'BN92 PLAIN HONGKONG NOODLES', selector: '#article_product_5602' },
  // Hongkong BN CHOPSTICK
  { name: 'BN17 NANKING BEEF HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'BN18 ANISEED BEEF TENDON HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'BN19 WANTON HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'BN20 FRESH PRAWN DUMPLING HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'BN21 3KINDS MUSHROOM HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'BN22 DOUBLE PORK RIB HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'BN23 SZE TANTAN MIEN HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'BN90 BN MIX HONGKONG NOODLES', selector: '#article_product_13937' },
  { name: 'BN92 PLAIN CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'BN92 PLAIN HONGKONG NOODLES', selector: '#article_product_13937' },
  // Canton BN
  { name: 'BN17 NANKING BEEF CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'BN18 ANISEED BEEF TENDON CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'BN19 WANTON CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'BN20 FRESH PRAWN DUMPLING CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'BN21 3KINDS MUSHROOM CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'BN22 DOUBLE PORK RIB CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'BN23 SZE TANTAN MIEN CANTON NOODLES', selector: '#article_product_5605' },
  { name: 'BN90 BN MIX CANTON NOODLES', selector: '#article_product_5605' },  
  // Canton BN SOUP
  { name: 'BN17 NANKING BEEF CANTON NOODLES', selector: '#article_product_5602' },
  { name: 'BN18 ANISEED BEEF TENDON CANTON NOODLES', selector: '#article_product_5602' },
  { name: 'BN19 WANTON CANTON NOODLES', selector: '#article_product_5602' },
  { name: 'BN20 FRESH PRAWN DUMPLING CANTON NOODLES', selector: '#article_product_5602' },
  { name: 'BN21 3KINDS MUSHROOM CANTON NOODLES', selector: '#article_product_5602' },
  { name: 'BN22 DOUBLE PORK RIB CANTON NOODLES', selector: '#article_product_5602' },
  { name: 'BN23 SZE TANTAN MIEN CANTON NOODLES', selector: '#article_product_5602' },
  { name: 'BN90 BN MIX CANTON NOODLES', selector: '#article_product_5602' },  
  // Canton BN CHOPSTICK
  { name: 'BN17 NANKING BEEF CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'BN18 ANISEED BEEF TENDON CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'BN19 WANTON CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'BN20 FRESH PRAWN DUMPLING CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'BN21 3KINDS MUSHROOM CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'BN22 DOUBLE PORK RIB CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'BN23 SZE TANTAN MIEN CANTON NOODLES', selector: '#article_product_13937' },
  { name: 'BN90 BN MIX CANTON NOODLES', selector: '#article_product_13937' },  
  // BN Flat Shanghai
  { name: 'BN17 NANKING BEEF FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'BN18 ANISEED BEEF TENDON FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'BN19 WANTON FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'BN20 FRESH PRAWN DUMPLING FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'BN21 3KINDS MUSHROOM FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'BN22 DOUBLE PORK RIB FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'BN23 SZE TANTAN MIEN FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'BN90 BN MIX FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  { name: 'BN92 PLAIN FLAT SHANGHAI NOODLES', selector: '#article_product_5605' },
  // BN Flat Shanghai SOUP
  { name: 'BN17 NANKING BEEF FLAT SHANGHAI NOODLES', selector: '#article_product_5602' },
  { name: 'BN18 ANISEED BEEF TENDON FLAT SHANGHAI NOODLES', selector: '#article_product_5602' },
  { name: 'BN19 WANTON FLAT SHANGHAI NOODLES', selector: '#article_product_5602' },
  { name: 'BN20 FRESH PRAWN DUMPLING FLAT SHANGHAI NOODLES', selector: '#article_product_5602' },
  { name: 'BN21 3KINDS MUSHROOM FLAT SHANGHAI NOODLES', selector: '#article_product_5602' },
  { name: 'BN22 DOUBLE PORK RIB FLAT SHANGHAI NOODLES', selector: '#article_product_5602' },
  { name: 'BN23 SZE TANTAN MIEN FLAT SHANGHAI NOODLES', selector: '#article_product_5602' },
  { name: 'BN90 BN MIX FLAT SHANGHAI NOODLES', selector: '#article_product_5602' },
  { name: 'BN92 PLAIN FLAT SHANGHAI NOODLES', selector: '#article_product_5602' },
  // BN Flat Shanghai CHOPSTICK
  { name: 'BN17 NANKING BEEF FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'BN18 ANISEED BEEF TENDON FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'BN19 WANTON FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'BN20 FRESH PRAWN DUMPLING FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'BN21 3KINDS MUSHROOM FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'BN22 DOUBLE PORK RIB FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'BN23 SZE TANTAN MIEN FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'BN90 BN MIX FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  { name: 'BN92 PLAIN FLAT SHANGHAI NOODLES', selector: '#article_product_13937' },
  // BN Herb
  { name: 'BN17 NANKING BEEF HERB NOODLES', selector: '#article_product_5605' },
  { name: 'BN18 ANISEED BEEF TENDON HERB NOODLES', selector: '#article_product_5605' },
  { name: 'BN19 WANTON HERB NOODLES', selector: '#article_product_5605' },
  { name: 'BN20 FRESH PRAWN DUMPLING HERB NOODLES', selector: '#article_product_5605' },
  { name: 'BN21 3KINDS MUSHROOM HERB NOODLES', selector: '#article_product_5605' },
  { name: 'BN22 DOUBLE PORK RIB HERB NOODLES', selector: '#article_product_5605' },
  { name: 'BN23 SZE TANTAN MIEN HERB NOODLES', selector: '#article_product_5605' },
  { name: 'BN90 BN MIX HERB NOODLES', selector: '#article_product_5605' },
  { name: 'BN92 PLAIN HERB NOODLES', selector: '#article_product_5605' },
  // BN Herb SOUP
  { name: 'BN17 NANKING BEEF HERB NOODLES', selector: '#article_product_5602' },
  { name: 'BN18 ANISEED BEEF TENDON HERB NOODLES', selector: '#article_product_5602' },
  { name: 'BN19 WANTON HERB NOODLES', selector: '#article_product_5602' },
  { name: 'BN20 FRESH PRAWN DUMPLING HERB NOODLES', selector: '#article_product_5602' },
  { name: 'BN21 3KINDS MUSHROOM HERB NOODLES', selector: '#article_product_5602' },
  { name: 'BN22 DOUBLE PORK RIB HERB NOODLES', selector: '#article_product_5602' },
  { name: 'BN23 SZE TANTAN MIEN HERB NOODLES', selector: '#article_product_5602' },
  { name: 'BN90 BN MIX HERB NOODLES', selector: '#article_product_5602' },
  { name: 'BN92 PLAIN HERB NOODLES', selector: '#article_product_5602' },
  // BN Herb CHOPSTICK
  { name: 'BN17 NANKING BEEF HERB NOODLES', selector: '#article_product_13937' },
  { name: 'BN18 ANISEED BEEF TENDON HERB NOODLES', selector: '#article_product_13937' },
  { name: 'BN19 WANTON HERB NOODLES', selector: '#article_product_13937' },
  { name: 'BN20 FRESH PRAWN DUMPLING HERB NOODLES', selector: '#article_product_13937' },
  { name: 'BN21 3KINDS MUSHROOM HERB NOODLES', selector: '#article_product_13937' },
  { name: 'BN22 DOUBLE PORK RIB HERB NOODLES', selector: '#article_product_13937' },
  { name: 'BN23 SZE TANTAN MIEN HERB NOODLES', selector: '#article_product_13937' },
  { name: 'BN90 BN MIX HERB NOODLES', selector: '#article_product_13937' },
  { name: 'BN92 PLAIN HERB NOODLES', selector: '#article_product_13937' },
  // BN EMPRESS
  { name: 'BN17 NANKING BEEF EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'BN18 ANISEED BEEF TENDON EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'BN19 WANTON EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'BN20 FRESH PRAWN DUMPLING EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'BN21 3KINDS MUSHROOM EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'BN22 DOUBLE PORK RIB EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'BN23 SZE TANTAN MIEN EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'BN90 BN MIX EMPRESS NOODLES', selector: '#article_product_5605' },
  { name: 'BN92 PLAIN EMPRESS NOODLES', selector: '#article_product_5605' },
  // BN EMPRESS SOUP
  { name: 'BN17 NANKING BEEF EMPRESS NOODLES', selector: '#article_product_5602' },
  { name: 'BN18 ANISEED BEEF TENDON EMPRESS NOODLES', selector: '#article_product_5602' },
  { name: 'BN19 WANTON EMPRESS NOODLES', selector: '#article_product_5602' },
  { name: 'BN20 FRESH PRAWN DUMPLING EMPRESS NOODLES', selector: '#article_product_5602' },
  { name: 'BN21 3KINDS MUSHROOM EMPRESS NOODLES', selector: '#article_product_5602' },
  { name: 'BN22 DOUBLE PORK RIB EMPRESS NOODLES', selector: '#article_product_5602' },
  { name: 'BN23 SZE TANTAN MIEN EMPRESS NOODLES', selector: '#article_product_5602' },
  { name: 'BN90 BN MIX EMPRESS NOODLES', selector: '#article_product_5602' },
  { name: 'BN92 PLAIN EMPRESS NOODLES', selector: '#article_product_5602' },
  // BN EMPRESS CHOPSTICK
  { name: 'BN17 NANKING BEEF EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'BN18 ANISEED BEEF TENDON EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'BN19 WANTON EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'BN20 FRESH PRAWN DUMPLING EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'BN21 3KINDS MUSHROOM EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'BN22 DOUBLE PORK RIB EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'BN23 SZE TANTAN MIEN EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'BN90 BN MIX EMPRESS NOODLES', selector: '#article_product_13937' },
  { name: 'BN92 PLAIN EMPRESS NOODLES', selector: '#article_product_13937' },
  // BN WHOLE WHEAT NOODLES
  { name: 'BN17 NANKING BEEF WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'BN18 ANISEED BEEF TENDON WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'BN19 WANTON WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'BN20 FRESH PRAWN DUMPLING WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'BN21 3KINDS MUSHROOM WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'BN22 DOUBLE PORK RIB WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'BN23 SZE TANTAN MIEN WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'BN90 BN MIX WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  { name: 'BN92 PLAIN WHOLE WHEAT NOODLES', selector: '#article_product_5605' },
  // BN WHOLE WHEAT NOODLES SOUP
  { name: 'BN17 NANKING BEEF WHOLE WHEAT NOODLES', selector: '#article_product_5602' },
  { name: 'BN18 ANISEED BEEF TENDON WHOLE WHEAT NOODLES', selector: '#article_product_5602' },
  { name: 'BN19 WANTON WHOLE WHEAT NOODLES', selector: '#article_product_5602' },
  { name: 'BN20 FRESH PRAWN DUMPLING WHOLE WHEAT NOODLES', selector: '#article_product_5602' },
  { name: 'BN21 3KINDS MUSHROOM WHOLE WHEAT NOODLES', selector: '#article_product_5602' },
  { name: 'BN22 DOUBLE PORK RIB WHOLE WHEAT NOODLES', selector: '#article_product_5602' },
  { name: 'BN23 SZE TANTAN MIEN WHOLE WHEAT NOODLES', selector: '#article_product_5602' },
  { name: 'BN90 BN MIX WHOLE WHEAT NOODLES', selector: '#article_product_5602' },
  { name: 'BN92 PLAIN WHOLE WHEAT NOODLES', selector: '#article_product_5602' },
  // BN WHOLE WHEAT NOODLES CHOPSTICK
  { name: 'BN17 NANKING BEEF WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'BN18 ANISEED BEEF TENDON WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'BN19 WANTON WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'BN20 FRESH PRAWN DUMPLING WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'BN21 3KINDS MUSHROOM WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'BN22 DOUBLE PORK RIB WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'BN23 SZE TANTAN MIEN WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'BN90 BN MIX WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  { name: 'BN92 PLAIN WHOLE WHEAT NOODLES', selector: '#article_product_13937' },
  // Yee Mien Noodles
  { name: 'YM2 FRIED WANTON', selector: '#article_product_5605' },
  // Superior Soup
  { name: 'SS41 NANKING BEEF', selector: '#article_product_5605' },
  { name: 'SS42 ANISEED BEEF TENDON', selector: '#article_product_5605' },
  { name: 'SS43 WANTON', selector: '#article_product_5605' },
  { name: 'SS44 FRESH PRAWN DUMPLING', selector: '#article_product_5605' },
  { name: 'SS45 CRAB CORN SOUP', selector: '#article_product_5605' },
  // Special Fried Rice
  { name: 'SFR29 SOUFFLE FR W/SAUCE', selector: '#article_product_5605' },
  { name: 'SFR29 SOUFFLE FR W/SAUCE', selector: '#article_product_5605' },
  { name: 'SFR30 FOOKIEN FR W/SAUCE', selector: '#article_product_5605' },
  { name: 'SFR30 FOOKIEN FR W/SAUCE', selector: '#article_product_5605' },
  { name: 'SFR31 SALTED FISH FR', selector: '#article_product_5605' },
  { name: 'SFR32 CHINESE BAGOONG W/L', selector: '#article_product_5605' },
  { name: 'SFR45 YANG CHOW FR', selector: '#article_product_5605' },
  { name: 'SFR46 NP SPECIAL FR W/SAU', selector: '#article_product_5605' },
  { name: 'SFR46 NP SPECIAL FR W/SAU', selector: '#article_product_5605' },
  { name: 'SFR59 PINEAPPLE FR', selector: '#article_product_5605' },
  { name: 'SFR60 WOK GARLIC FR', selector: '#article_product_5605' },
  { name: 'SFR61 CRAB MEAT FR', selector: '#article_product_5605' },
  // Service With Rice
  { name: 'SR24 WHITE CHICKEN', selector: '#article_product_5603' },
  { name: 'SR25 NANKING BEEF', selector: '#article_product_5603' },
  { name: 'SR26 ANISEED BEEF TENDON', selector: '#article_product_5603' },
  { name: 'SR27 DOUBLE PORK RIB', selector: '#article_product_5603' },
  { name: 'SR28 SOY SAUCE CHICKEN', selector: '#article_product_5603' },
  { name: 'SR87 LECHON MACAU OVR FR', selector: '#article_product_5605' },
  // Service With Rice EXTRA RICE
  { name: 'SR24 WHITE CHICKEN', selector: '#article_product_5602' },
  { name: 'SR25 NANKING BEEF', selector: '#article_product_5602' },
  { name: 'SR26 ANISEED BEEF TENDON', selector: '#article_product_5602' },
  { name: 'SR27 DOUBLE PORK RIB', selector: '#article_product_5602' },
  { name: 'SR28 SOY SAUCE CHICKEN', selector: '#article_product_5602' },
  // Signature Dishes
  { name: 'HAPPY BIRTHDAY NOODLES', selector: '#article_product_5607' },
  { name: 'ND49 FRIED BEANCRD W/MUSH', selector: '#article_product_5603' },
  { name: 'ND51A 3MUSH W/KAILAN OS', selector: '#article_product_5603' },
  { name: 'ND51B 3MUSH W/B.FLOWER OS', selector: '#article_product_5603' },
  { name: 'ND52A NP TOASTED NOODLES', selector: '#article_product_5605' },
  { name: 'ND52B NP CHOW MIEN', selector: '#article_product_5606' },
  { name: 'ND53A KING DAO SPARERIBS', selector: '#article_product_5603' },
  { name: 'ND53B SALT&PEPPR SPARERBS', selector: '#article_product_5603' },
  { name: 'ND54 BLACK PEPPERBEEF STR', selector: '#article_product_5603' },
  { name: 'ND72 TAIWAN PECHAY CLAMS', selector: '#article_product_5606' },
  { name: 'ND73 SALTED GARLIC SQUID', selector: '#article_product_5603' },
  { name: 'ND74 BEEF W/BROC KAILAN', selector: '#article_product_5606' },
  { name: 'ND77 VINEGARED TOFU', selector: '#article_product_5606' },
  { name: 'ND78 MANCHURIAN CALAMARES', selector: '#article_product_5603' },
  { name: 'ND80 BONELSS FRIED CHX CH', selector: '#article_product_5603' },
  { name: 'ND81 WOK FISH FILLET', selector: '#article_product_5603' },
  { name: 'ND83 SWEET CHILI PRAWNS', selector: '#article_product_5603' },
  { name: 'ND84 SALTED PEPPER PRAWNS', selector: '#article_product_5603' },
  { name: 'ND85 BONELES HONEY GARLIC PORK SPARERIBS', selector: '#article_product_5603' },
  { name: 'ND86 MAPO TOFU', selector: '#article_product_5604' },
  { name: 'ND87 SNOW FISH w/BBS', selector: '#article_product_5603' },
  { name: 'ND89 CRABMEAT LOMI', selector: '#article_product_5605' },
  { name: 'ND90 SPICY SEAFOOD CHAMI', selector: '#article_product_5603' },
  { name: 'TAIWAN GARLIC', selector: '#article_product_5606' },  
  // Best Sellers
  { name: 'BROCC FLOWER W/ GARLIC', selector: '#article_product_5606' },
  { name: 'ND48 CHINA CHICKEN', selector: '#article_product_5607' },
  { name: 'ND50A BROC KAILAN OS', selector: '#article_product_5603' },
  { name: 'ND50B BROC FLOWER OS', selector: '#article_product_5603' },
  { name: 'ND69 SHANGHAI CHICKEN', selector: '#article_product_5607' },
  { name: 'ND70 SWEET & SOUR F-FILET', selector: '#article_product_5603' },
  { name: 'ND71 SWEET & SOUR PORK', selector: '#article_product_5606' },
  { name: 'ND75 BEEF W/BROC FLOWER', selector: '#article_product_5606' },
  { name: 'ND76 AMPALAYA CON CARNE', selector: '#article_product_5606' },
  { name: 'ND79 BONELSS LEMON CHIX', selector: '#article_product_5603' },
  { name: 'ND82 TOFU VEGGIE STIR FRY', selector: '#article_product_5606' },
  // Hot Pot Dishes
  { name: 'HP1 NANKING BEEF/TENDON', selector: '#article_product_5604' },
  { name: 'HP2 FISH FILLET W/TOFU', selector: '#article_product_5605' },
  { name: 'HP3 LCHN MACAU W/EGGPLANT', selector: '#article_product_5605' },  
  // Roast Specialties
  { name: 'RS54 ROAST COMBI PLATTER', selector: '#article_product_5607' },
  { name: 'RS56 BBQ PORK ASADO', selector: '#article_product_5603' },
  { name: 'RS58 DRIED PORK SAUSAGE', selector: '#article_product_5603' },
  { name: 'RS86 LECHON MACAU', selector: '#article_product_5603' },
  // SUPERIOR CONGEE
  { name: 'SC32L CRYSTAL PRAWN LP', selector: '#article_product_5604' },
  { name: 'SC32R CRYSTAL PRAWN RG', selector: '#article_product_5605' },
  { name: 'SC33L P.CLAM/TNDR BEEF LP', selector: '#article_product_5604' },
  { name: 'SC33R P.CLAM/TNDR BEEF RG', selector: '#article_product_5605' },
  { name: 'SC47 NP SUPERIOR CONGEE', selector: '#article_product_5605' },  
  // CONGEE
  { name: 'C36L PORK BOLA CONGEE LP', selector: '#article_product_5604' },
  { name: 'C36R PORK BOLA CONGEE RG', selector: '#article_product_5605' },
  { name: 'C37L CHCKN BALL CONGEE LP', selector: '#article_product_5604' },
  { name: 'C37R CHCKN BALL CONGEE RG', selector: '#article_product_5605' },
  { name: 'C38L FISH CONGEE LP', selector: '#article_product_5604' },
  { name: 'C38R FISH CONGEE RG', selector: '#article_product_5605' },
  { name: 'C39L PORK/C.EGG CONGEE LP', selector: '#article_product_5604' },
  { name: 'C39R PORK/C.EGG CONGEE RG', selector: '#article_product_5605' },
  { name: 'C40L SLICED BEEF CNGEE LP', selector: '#article_product_5604' },
  { name: 'C40R SLICED BEEF CNGEE RG', selector: '#article_product_5605' },
  { name: 'C90 PLAIN CONGEE', selector: '#article_product_5605' },
  { name: 'CHICKEN CONGEE', selector: '#article_product_5605' },
  // Dessert
  { name: 'D60 HERB JELLY W/T.FRUITS', selector: '#article_product_5602' },
  { name: 'D62A GABI BUTCHI 3', selector: '#article_product_5602' },
  { name: 'D63 ALMOND JELLY W/LYCHEE', selector: '#article_product_5602' },
  { name: 'D64 B&W GULAMAN W/T.FRUIT', selector: '#article_product_5602' },
  { name: 'D65 HERB JELLY W/LYCHEE', selector: '#article_product_5602' },
  { name: 'D66 ALMOND JELLY W/TFRUIT', selector: '#article_product_5602' },
  { name: 'D67 ALMOND JELLY W/ FRESH MANGO', selector: '#article_product_5602' },
  { name: 'D69 FRESH MANGO TAPIOCA', selector: '#article_product_5602' },
  { name: 'D70 B&W GULAMAN W/SAGO', selector: '#article_product_5602' },
  { name: 'D75 B&W GULAMAN', selector: '#article_product_5602' },  
  // Drinks
  { name: 'DR01 CHRYSANTHEMUM JUICE', selector: '#article_product_13647' },
  { name: 'DR02A WATERMELON SHAKE', selector: '#article_product_13647' },
  { name: 'DR02B MANGO SHAKE', selector: '#article_product_13647' },
  { name: 'DR02C LYCHEE SHAKE', selector: '#article_product_13647' },
  { name: 'DR02D PINEAPPLE SHAKE', selector: '#article_product_13647' },
  { name: 'DR04 COLD SOYA BEAN MILK', selector: '#article_product_13647' },
  { name: 'DR05 NESTEA ICED TEA', selector: '#article_product_13647' },
  { name: 'DR06 FRESH LEMONADE', selector: '#article_product_13647' },
  { name: 'DR07 FOUR SEASONS', selector: '#article_product_13647' },
  { name: 'DR09 APPLE JUICE', selector: '#article_product_13647' },
  { name: 'DR10 HONEY LEMONADE', selector: '#article_product_13647' },
  { name: 'DR11 NESTEA LEMON ICEDTEA', selector: '#article_product_13647' },
  { name: 'DR18 NAI CHA W/ JELLY', selector: '#article_product_13647' },
  { name: 'DR21 BUBBLE FRESH MANGO', selector: '#article_product_13647' },
  { name: 'DR22 CALAMANSI JUICE', selector: '#article_product_13647' },
  // Add more products here          
];

// ==============================
// Step 4: Wait for the first product container before running all handlers
waitForProductById('article_product_5605', () => {
  productsToHandle.forEach(p => handleProductOrders(p.name, p.selector));

  // Safe place for "always click these two"
  ['#article_product_5594', '#article_product_13938'].forEach(id => {
    document.querySelector(id)?.click();
  });
});
})();

